#!/usr/bin/env bash

set -Eeuo pipefail

if [[ -z "$(command -v cpanm)" ]]; then
	echo 'Please install cpanm'
	exit 1
fi

echo 'Installing seacan from git (on cpan it is too old)...'
cpanm -nq https://github.com/gugod/Seacan/tarball/master
cpanm -nq https://github.com/perltidy/perltidy/archive/refs/tags/20200907.tar.gz
echo
echo 'Installing proper versions of broken modules...'
# cpanm -nq --force https://cpan.metacpan.org/authors/id/E/ET/ETHER/Devel-Declare-0.006019.tar.gz
# cpanm -nq --force https://cpan.metacpan.org/authors/id/B/BA/BARNEY/Net-Amazon-S3-0.91.tar.gz
echo
echo 'Installing prereqs from cpanfile...'
pushd tools &>/dev/null
cpanm -nq --installdeps .
popd &>/dev/null
echo
echo 'Installing dzil plugins and prereqs...'
dzil authordeps --missing | cpanm -n -q
echo
echo 'Installing autoguessed prereqs...'
dzil listdeps --author --develop --missing | cpanm -n -q
